version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:delegated
    environment:
      - POSTGRES_USER=layman
      - POSTGRES_PASSWORD=layman

  web:
    build: .
    command: >
      sh -c "./wait-for-postgres.sh python manage.py runserver 0.0.0.0:8080"
    environment:
      - DATABASE_NAME=layman
      - DATABASE_USER=layman
      - DATABASE_PASSWORD=layman
      - DATABASE_HOST=db
    volumes:
      - .:/code:cached
    ports:
      - '8080:8080'
    depends_on:
      - db
