# Generated by Django 3.2 on 2022-01-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220103_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='business_name',
            field=models.CharField(default='Sky Papers', max_length=250),
        ),
    ]
