# Generated by Django 3.2 on 2022-01-03 05:31

from django.db import migrations, models
import django.db.models.deletion
import utils.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_warehouse_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='line_item_set', to='core.order'),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(blank=True, help_text='PO number for this shipment', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiving_centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_shipments', to='core.warehouse')),
            ],
            options={
                'abstract': False,
            },
            bases=(utils.models.AutoUpdateMixin, models.Model),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='receipt',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.receipt'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='receipt',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='line_item_set', to='core.receipt'),
        ),
    ]
