# Generated by Django 3.2 on 2022-01-03 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220103_0531'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='location',
            name='warehouse',
        ),
        migrations.AlterUniqueTogether(
            name='lotcode',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lotcode',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='receiving_centre',
        ),
        migrations.RemoveConstraint(
            model_name='inventory',
            name='unique_with_lot_code',
        ),
        migrations.RemoveConstraint(
            model_name='inventory',
            name='unique_without_lot_code',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='location',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='lot_code',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='inventoryadjustment',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='receipt',
        ),
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_type',
            field=models.CharField(choices=[('paper', 'Paper'), ('ink', 'Ink'), ('plate', 'Plate')], db_index=True, default='paper', max_length=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sku',
            field=models.CharField(db_index=True, default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='variant',
            field=models.CharField(db_index=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineitem',
            name='inventory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='core.inventory'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='LotCode',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
