# Generated by Django 3.2 on 2022-01-03 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220103_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='line_item_set', to='core.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.customer'),
        ),
    ]
