# Generated by Django 3.2 on 2022-01-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220103_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='fulfilled',
        ),
        migrations.RemoveField(
            model_name='inventoryadjustment',
            name='fulfilled_change',
        ),
        migrations.RemoveField(
            model_name='inventoryadjustmentlog',
            name='absolute_post_fulfilled',
        ),
        migrations.RemoveField(
            model_name='inventoryadjustmentlog',
            name='absolute_pre_fulfilled',
        ),
        migrations.RemoveField(
            model_name='inventoryadjustmentlog',
            name='fulfilled_change',
        ),
        migrations.RemoveField(
            model_name='order',
            name='error_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='internal_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='print_priority',
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
