# Generated by Django 3.2 on 2022-01-07 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220107_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='name',
        ),
    ]
